# Generated by Django 5.0.6 on 2024-07-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmplitudeCriticite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieDechet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Criticite',
            fields=[
                ('id_criticite', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé')], max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('OCCASION', 'Occasion')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type_ordure',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé')], max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DepotOrdure',
            fields=[
                ('id_depot', models.AutoField(primary_key=True, serialize=False)),
                ('localisation', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('date_signalement', models.DateField()),
                ('description', models.TextField()),
                ('id_niveau_criticite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.amplitudecriticite')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoriedechet')),
                ('id_reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id_annonce', models.AutoField(primary_key=True, serialize=False)),
                ('date_publication', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('VENDU', 'Vendu')], max_length=10)),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
                ('id_acheteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('date_transaction', models.DateField()),
                ('montant', models.FloatField()),
                ('id_annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.annonce')),
                ('id_acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_acheteur', to='app.utilisateur')),
                ('id_vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_vendeur', to='app.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id_suivi', models.AutoField(primary_key=True, serialize=False)),
                ('date_suivi', models.DateField()),
                ('id_depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.depotordure')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='id_vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur'),
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id_panier', models.AutoField(primary_key=True, serialize=False)),
                ('id_produit', models.ManyToManyField(to='app.produit')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateField()),
                ('id_destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_destinataire', to='app.utilisateur')),
                ('id_expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_expediteur', to='app.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_commentaire', models.AutoField(primary_key=True, serialize=False)),
                ('texte', models.TextField()),
                ('id_annonce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.annonce')),
                ('id_depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.depotordure')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur')),
            ],
        ),
    ]
