# Generated by Django 5.0.6 on 2024-07-05 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id_annonce', models.AutoField(primary_key=True, serialize=False)),
                ('date_publication', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('VENDU', 'Vendu')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_commentaire', models.AutoField(primary_key=True, serialize=False)),
                ('texte', models.TextField()),
                ('id_annonce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Criticite',
            fields=[
                ('id_criticite', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé')], max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DepotOrdure',
            fields=[
                ('id_depot', models.AutoField(primary_key=True, serialize=False)),
                ('localisation', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('date_signalement', models.DateField()),
                ('id_niveau_criticite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.criticite')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id_panier', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('categorie', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('OCCASION', 'Occasion')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id_suivi', models.AutoField(primary_key=True, serialize=False)),
                ('date_suivi', models.DateField()),
                ('id_depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.depotordure')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('date_transaction', models.DateField()),
                ('montant', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='id_depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.depotordure'),
        ),
        migrations.AddField(
            model_name='panier',
            name='id_produit',
            field=models.ManyToManyField(to='app.produit'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='id_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='id_annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.annonce'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='id_acheteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_acheteur', to='app.utilisateur'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='id_vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_vendeur', to='app.utilisateur'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='id_utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur'),
        ),
        migrations.AddField(
            model_name='produit',
            name='id_vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur'),
        ),
        migrations.AddField(
            model_name='panier',
            name='id_utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur'),
        ),
        migrations.AddField(
            model_name='message',
            name='id_destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_destinataire', to='app.utilisateur'),
        ),
        migrations.AddField(
            model_name='message',
            name='id_expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_expediteur', to='app.utilisateur'),
        ),
        migrations.AddField(
            model_name='depotordure',
            name='id_reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='id_utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='id_acheteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.utilisateur'),
        ),
    ]
